dist: trusty
sudo: false
language: python
python:
- '3.3'

jdk:
- oraclejdk8

addons:
  sonarqube:
    organization: "martiuripariu-github"
    token:
      secure: "$SONAR_TOKEN"

branches:
  only:
  - master
  - desenvolvemento
  
script:
- sonar-scanner


